Encore16Backend/ByeBuyigApp

- src/components/Base/Header/NavB.js
- src/hooks/GetBestItems.js
- src/hooks/pdtHook/GetCate.js
- src/hooks/pdtHook/GetTotalPage.js
> searchCataApply2

- src/components/Base/Header/NavB.js
- src/css/drop.css
> selectboxDesign

- src/components/Base/Header/NavB.js
- src/components/Base/main/MyCard.js
- src/css/drop.css
> modifySelectDesign

- src/components/Base/Header/NavB.js
- src/css/drop.css
> modifyMargin

- src/App.css
- src/components/Base/Header/NavB.js
- src/components/detail/desc.js
- src/components/detail/reviewview.js
- src/modals/SignInModal.js
- src/pages/MyReview.js
> reviewModify

- src/App.css
- src/App.js
- src/components/Base/Header/NavB.js
- src/components/detail/makereview.js
- src/css/desc.css
- src/hooks/postRefresh.js
- src/modals/BeforeOrder.js
- src/modals/SignInModal.js
- src/modals/SignUpModal.js
- src/pages/CateList.js
- src/pages/Order.js
- src/pages/OrderResult.js
- src/pages/SearchPage.js
- src/pages/ShoppingBasket.js
> afterOrder

- src/App.css
- src/Routers.js
- src/components/Base/Header/NavB.js
- src/components/detail/desc.js
- src/modals/BeforeOrder.js
- src/modals/SignUpModal.js
- src/pages/CateList.js
- src/pages/ManageComent.js
- src/pages/ManageReview.js
- src/pages/ManageUser.js
> modified css

- src/App.js
- src/components/etc/MyCalendar.js
- src/pages/Order.js
> dateSearch

- src/components/etc/MyCalendar.js
- src/pages/Order.js
> searchdate2

- src/App.js
- src/pages/MyReview.js
- src/utils/setAuthorizationToken.js
> reviewDateSearch

- src/components/Base/Header/NavB.js
> searcgIcon

- src/Routers.js
- src/components/Base/Header/NavB.js
- src/components/detail/reviewview.js
- src/pages/InquiryDetail.js
- src/pages/MyInquiry.js
> detailInquiry

- src/components/Base/Header/NavB.js
- src/components/auth/PopupPostCode.js
- src/components/detail/desc.js
- src/components/detail/makereview.js
- src/components/detail/reviewview.js
- src/modals/BeforeOrder.js
- src/modals/SignInModal.js
- src/pages/InquiryDetail.js
- src/pages/MyInquiry.js
- src/pages/MyReview.js
- src/pages/Order.js
- src/pages/OrderResult.js
- src/pages/ShoppingBasket.js
> orderAndCamera

- src/modals/BeforeOrder.js
> orderModify

- src/pages/ManageInquiry.js
> Modifed axios

- src/App.js
- src/Routers.js
- src/components/Base/Header/NavB.js
- src/components/Base/main/Page.js
- src/hooks/GetMainItems.js
- src/pages/DetailPage.js
- src/pages/InquiryDetail.js
- src/pages/ManageProduct.js
- src/pages/ManageUser.js
- src/pages/MyInquiry.js
- src/pages/MyReview.js
- src/pages/Order.js
- src/pages/SearchPage.js
> calendarModify

- src/axiosproperties.js
- src/components/detail/desc.js
- src/components/detail/makereview.js
- src/modals/BeforeOrder.js
- src/pages/ManageProduct.js
- src/pages/MyReview.js
- src/pages/Order.js
- src/pages/OrderResult.js
- src/pages/SaveProduct.js
- src/pages/ShoppingBasket.js
getStringPrice and myorder myReview dateModify
> getStringPrice and myorder myReview dateModify

- src/modals/SignUpModal.js
- src/pages/Home.js
> ur modify4

- src/App.css
- src/components/auth/PopupPostCode.js
- src/components/detail/desc.js
- src/modals/CheckModal.js
- src/modals/SignUpModal.js
- src/pages/SaveProduct.js
> savepdt form

- src/App.js
- src/pages/SaveProduct.js
> savePdtImg Modify

- src/pages/ManageInquiry.js
- src/pages/ManageProduct.js
- src/pages/MyReview.js
> modify myreview

- src/components/detail/makereview.js
- src/modals/BeforeOrder.js
- src/modals/MakeReviewModal.js
- src/pages/ManageProduct.js
- src/pages/ManageReview.js
- src/pages/Order.js
> order review

- src/components/Base/main/Carsol.js
- src/components/admin/InquiryComponent.js
- src/components/detail/desc.js
- src/components/detail/makereview.js
- src/components/detail/reviewview.js
- src/hooks/GetMainItems.js
- src/hooks/pdtHook/GetTotalPage.js
- src/hooks/postRefresh.js
- src/modals/BeforeOrder.js
- src/modals/SignUpModal.js
- src/pages/DetailPage.js
- src/pages/ImgSearchList.js
- src/pages/ImgSearchPage.js
- src/pages/ManageInquiry.js
- src/pages/ManageProduct.js
- src/pages/ManageReview.js
- src/pages/ManageUser.js
- src/pages/MyInquiry.js
- src/pages/MyReview.js
- src/pages/Order.js
- src/pages/SaveProduct.js
- src/pages/ShoppingBasket.js
- src/pages/Update.js
> del console.log1

- src/components/Base/Header/NavB.js
- src/components/detail/desc.js
- src/modals/BeforeOrder.js
- src/modals/MakeReviewModal.js
- src/modals/SignUpModal.js
- src/pages/ManageProduct.js
- src/pages/Order.js
> 0323 order review

- src/axiosproperties.js
- src/pages/ImgSearchList.js
- src/pages/ManageProduct.js
- src/pages/SaveProduct.js
> beforeFinal
